# Generated by Django 3.2.15 on 2024-01-20 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('did', models.AutoField(primary_key=True, serialize=False)),
                ('dname', models.CharField(max_length=255, verbose_name='Doctor name')),
                ('ddegree', models.CharField(max_length=255)),
            ],
        ),
    ]
